name: Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v2

  semgrep:
    name: Semgrep Static Analysis
    runs-on: ubuntu-latest
    needs: codeql-analysis

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/ci

  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    needs: semgrep  # Opsiyonel: Semgrep tamamlandıktan sonra çalışır

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          config-path: ""       # Varsayılan kurallar seti kullanılacak
          verbose: true
